// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PanelForge.Infrastructure.Persistence;

#nullable disable

namespace PanelForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PanelForgeDbContext))]
    [Migration("20260921031219_AddMissingAuditColumns")]
    partial class AddMissingAuditColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.ExternalPreviewLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("WatermarkText")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("watermark_text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_external_preview_links_chapter_id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_external_preview_links_token_hash");

                    b.ToTable("external_preview_links", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.StudioWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("StorageQuotaBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("storage_quota_bytes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<long>("UsedStorageBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("used_storage_bytes");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_studio_workspaces_owner_id");

                    b.ToTable("studio_workspaces", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email_verification_token");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("email_verification_token_expires_at");

                    b.Property<string>("FirebaseUid")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_confirmed");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("password_reset_token_expires_at");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("two_factor_secret");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_firebase_uid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.UserRememberedDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("device_name");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TokenHash")
                        .HasDatabaseName("ix_user_remembered_devices_user_token");

                    b.ToTable("user_remembered_devices", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_members_workspace_user");

                    b.ToTable("workspace_members", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Bible.BibleEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details_json");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("priority");

                    b.Property<string>("ReferenceImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("reference_image_url");

                    b.Property<Guid>("SeriesBibleId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_bible_id");

                    b.Property<bool>("StrictCheck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("strict_check");

                    b.Property<string>("Subtitle")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subtitle");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_bible_entries_category");

                    b.HasIndex("SeriesBibleId")
                        .HasDatabaseName("ix_bible_entries_series_bible_id");

                    b.HasIndex("SeriesBibleId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_bible_entries_series_bible_id_code");

                    b.ToTable("bible_entries", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Bible.BibleEntryRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssociatedChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("associated_chapter_id");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid>("BibleEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("bible_entry_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_json");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("summary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("BibleEntryId")
                        .HasDatabaseName("ix_bible_entry_revisions_bible_entry_id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_bible_entry_revisions_content_hash");

                    b.HasIndex("BibleEntryId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_bible_entry_revisions_bible_entry_id_version");

                    b.ToTable("bible_entry_revisions", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Bible.SeriesBible", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .IsUnique()
                        .HasDatabaseName("ix_series_bibles_series_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_series_bibles_workspace_id");

                    b.ToTable("series_bibles", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ChapterNumber")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("chapter_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateOnly?>("TargetReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("target_release_date");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<long>("VersionVector")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version_vector");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_chapters_series_id");

                    b.HasIndex("SeriesId", "ChapterNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_chapters_series_number");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("element_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PanelId")
                        .HasColumnType("uuid")
                        .HasColumnName("panel_id");

                    b.Property<Guid?>("ScriptLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("script_line_id");

                    b.Property<Guid?>("SpeakerCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("speaker_character_id");

                    b.Property<string>("StyleProperties")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("style_properties")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("TransformGeometry")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("transform_geometry")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("ZIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("z_index");

                    b.HasKey("Id");

                    b.HasIndex("ScriptLineId");

                    b.HasIndex("SpeakerCharacterId");

                    b.HasIndex("PanelId", "ZIndex")
                        .HasDatabaseName("ix_elements_panel_zindex");

                    b.ToTable("elements", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_stage_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<int>("Dpi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(300)
                        .HasColumnName("dpi");

                    b.Property<int>("HeightPx")
                        .HasColumnType("int")
                        .HasColumnName("height_px");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LayoutFormat")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("layout_format");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int")
                        .HasColumnName("page_number");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("WidthPx")
                        .HasColumnType("int")
                        .HasColumnName("width_px");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("SceneId");

                    b.HasIndex("ChapterId", "PageNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_pages_chapter_number");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Panel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BoundingBox")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("bounding_box")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_stage_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<int>("PanelNumber")
                        .HasColumnType("int")
                        .HasColumnName("panel_number");

                    b.Property<int>("ReadingOrder")
                        .HasColumnType("int")
                        .HasColumnName("reading_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("PageId", "PanelNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_panels_page_number");

                    b.ToTable("panels", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Heading")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("heading");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SceneNumber")
                        .HasColumnType("int")
                        .HasColumnName("scene_number");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "SceneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_scenes_chapter_number");

                    b.ToTable("scenes", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.ScriptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("DialogueText")
                        .HasColumnType("text")
                        .HasColumnName("dialogue_text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LineOrder")
                        .HasColumnType("int")
                        .HasColumnName("line_order");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.Property<Guid?>("SpeakerCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("speaker_character_id");

                    b.Property<string>("StageDirection")
                        .HasColumnType("text")
                        .HasColumnName("stage_direction");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpeakerCharacterId");

                    b.HasIndex("SceneId", "LineOrder")
                        .HasDatabaseName("ix_script_lines_scene_order");

                    b.ToTable("script_lines", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PipelineDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_definition_id");

                    b.Property<string>("ReadingDirection")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reading_direction");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_series_workspace_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedRole")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("assigned_role");

                    b.Property<Guid>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<string>("Brief")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brief");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("due_date");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastFeedbackComment")
                        .HasColumnType("text")
                        .HasColumnName("last_feedback_comment");

                    b.Property<Guid>("PipelineStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_stage_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("priority");

                    b.Property<string>("ReferenceAssetUrlsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("reference_asset_urls_json");

                    b.Property<string>("ReferenceNotes")
                        .HasColumnType("text")
                        .HasColumnName("reference_notes");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_entity_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeUserId")
                        .HasDatabaseName("ix_assignments_assignee_user_id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_assignments_chapter_id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_assignments_due_date");

                    b.HasIndex("PipelineStageId")
                        .HasDatabaseName("ix_assignments_pipeline_stage_id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_assignments_series_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_assignments_status");

                    b.HasIndex("TargetEntityId")
                        .HasDatabaseName("ix_assignments_target_entity_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.PipelineDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_definitions_series_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_pipeline_definitions_workspace_id");

                    b.ToTable("pipeline_definitions", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.PipelineStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedRole")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("allowed_role");

                    b.Property<string>("ColorCode")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("color_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<int?>("EstimatedDurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_days");

                    b.Property<bool>("IsApprovalGate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approval_gate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInitial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_initial");

                    b.Property<bool>("IsTerminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PipelineDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_definition_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("slug");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer")
                        .HasColumnName("stage_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PipelineDefinitionId")
                        .HasDatabaseName("ix_pipeline_stages_pipeline_definition_id");

                    b.HasIndex("PipelineDefinitionId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_stages_definition_slug");

                    b.HasIndex("PipelineDefinitionId", "StageOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_stages_definition_stage_order");

                    b.ToTable("pipeline_stages", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.StageTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FromStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_stage_id");

                    b.Property<bool>("IsBackwardTransition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_backward_transition");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PipelineDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_definition_id");

                    b.Property<string>("RequiredRole")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("required_role");

                    b.Property<bool>("RequiresComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_comment");

                    b.Property<Guid>("ToStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_stage_id");

                    b.Property<string>("TransitionName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("transition_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FromStageId")
                        .HasDatabaseName("ix_stage_transitions_from_stage_id");

                    b.HasIndex("PipelineDefinitionId")
                        .HasDatabaseName("ix_stage_transitions_pipeline_definition_id");

                    b.HasIndex("ToStageId")
                        .HasDatabaseName("ix_stage_transitions_to_stage_id");

                    b.HasIndex("PipelineDefinitionId", "FromStageId", "ToStageId")
                        .IsUnique()
                        .HasDatabaseName("ix_stage_transitions_def_from_to");

                    b.ToTable("stage_transitions", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.WorkflowTransitionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("FromStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_stage_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ToStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_stage_id");

                    b.Property<Guid>("TriggeredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_workflow_transition_logs_entity_id");

                    b.HasIndex("FromStageId");

                    b.HasIndex("ToStageId")
                        .HasDatabaseName("ix_workflow_transition_logs_to_stage_id");

                    b.ToTable("workflow_transition_logs", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.ExternalPreviewLink", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Chapter", null)
                        .WithMany("ExternalPreviewLinks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Auth.User", "CreatedByUser")
                        .WithMany("CreatedPreviewLinks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.StudioWorkspace", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Auth.User", "Owner")
                        .WithMany("OwnedWorkspaces")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.UserRememberedDevice", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.WorkspaceMember", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Auth.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Auth.StudioWorkspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Bible.BibleEntry", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Bible.SeriesBible", "SeriesBible")
                        .WithMany("Entries")
                        .HasForeignKey("SeriesBibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeriesBible");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Bible.BibleEntryRevision", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Bible.BibleEntry", "BibleEntry")
                        .WithMany("Revisions")
                        .HasForeignKey("BibleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleEntry");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Bible.SeriesBible", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Series", "Series")
                        .WithOne("Bible")
                        .HasForeignKey("PanelForge.Domain.Entities.Bible.SeriesBible", "SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Auth.StudioWorkspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Chapter", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Series", "Series")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Element", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Panel", "Panel")
                        .WithMany("Elements")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Content.ScriptLine", "ScriptLine")
                        .WithMany("BoundElements")
                        .HasForeignKey("ScriptLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PanelForge.Domain.Entities.Bible.BibleEntry", "SpeakerCharacter")
                        .WithMany()
                        .HasForeignKey("SpeakerCharacterId");

                    b.Navigation("Panel");

                    b.Navigation("ScriptLine");

                    b.Navigation("SpeakerCharacter");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Page", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Chapter", "Chapter")
                        .WithMany("Pages")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Workflow.PipelineStage", "CurrentStage")
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PanelForge.Domain.Entities.Content.Scene", "Scene")
                        .WithMany("Pages")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("CurrentStage");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Panel", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Workflow.PipelineStage", "CurrentStage")
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PanelForge.Domain.Entities.Content.Page", "Page")
                        .WithMany("Panels")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentStage");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Scene", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Chapter", "Chapter")
                        .WithMany("Scenes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.ScriptLine", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Scene", "Scene")
                        .WithMany("ScriptLines")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Bible.BibleEntry", "SpeakerCharacter")
                        .WithMany()
                        .HasForeignKey("SpeakerCharacterId");

                    b.Navigation("Scene");

                    b.Navigation("SpeakerCharacter");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Series", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Auth.StudioWorkspace", "Workspace")
                        .WithMany("Series")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.Assignment", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Auth.User", "Assignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssigneeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Content.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Workflow.PipelineStage", "Stage")
                        .WithMany("Assignments")
                        .HasForeignKey("PipelineStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Content.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Chapter");

                    b.Navigation("Series");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.PipelineDefinition", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Series", "Series")
                        .WithOne("PipelineDefinition")
                        .HasForeignKey("PanelForge.Domain.Entities.Workflow.PipelineDefinition", "SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PanelForge.Domain.Entities.Auth.StudioWorkspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.PipelineStage", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Workflow.PipelineDefinition", "PipelineDefinition")
                        .WithMany("Stages")
                        .HasForeignKey("PipelineDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineDefinition");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.StageTransition", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Workflow.PipelineStage", "FromStage")
                        .WithMany("OutgoingTransitions")
                        .HasForeignKey("FromStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Workflow.PipelineDefinition", "PipelineDefinition")
                        .WithMany("Transitions")
                        .HasForeignKey("PipelineDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Workflow.PipelineStage", "ToStage")
                        .WithMany("IncomingTransitions")
                        .HasForeignKey("ToStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStage");

                    b.Navigation("PipelineDefinition");

                    b.Navigation("ToStage");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.WorkflowTransitionLog", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Workflow.PipelineStage", "FromStage")
                        .WithMany()
                        .HasForeignKey("FromStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PanelForge.Domain.Entities.Workflow.PipelineStage", "ToStage")
                        .WithMany()
                        .HasForeignKey("ToStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStage");

                    b.Navigation("ToStage");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.StudioWorkspace", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedPreviewLinks");

                    b.Navigation("OwnedWorkspaces");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Bible.BibleEntry", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Bible.SeriesBible", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Chapter", b =>
                {
                    b.Navigation("ExternalPreviewLinks");

                    b.Navigation("Pages");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Page", b =>
                {
                    b.Navigation("Panels");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Panel", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Scene", b =>
                {
                    b.Navigation("Pages");

                    b.Navigation("ScriptLines");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.ScriptLine", b =>
                {
                    b.Navigation("BoundElements");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Series", b =>
                {
                    b.Navigation("Bible");

                    b.Navigation("Chapters");

                    b.Navigation("PipelineDefinition");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.PipelineDefinition", b =>
                {
                    b.Navigation("Stages");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Workflow.PipelineStage", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("IncomingTransitions");

                    b.Navigation("OutgoingTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
