// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PanelForge.Infrastructure.Persistence;

#nullable disable

namespace PanelForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PanelForgeDbContext))]
    [Migration("20260912143610_AddUserPasswordHash")]
    partial class AddUserPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.ExternalPreviewLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("token_hash");

                    b.Property<string>("WatermarkText")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("watermark_text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_external_preview_links_chapter_id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_external_preview_links_token_hash");

                    b.ToTable("external_preview_links", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.StudioWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("StorageQuotaBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("storage_quota_bytes");

                    b.Property<long>("UsedStorageBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("used_storage_bytes");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_studio_workspaces_owner_id");

                    b.ToTable("studio_workspaces", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_firebase_uid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_members_workspace_user");

                    b.ToTable("workspace_members", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ChapterNumber")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("chapter_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateOnly?>("TargetReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("target_release_date");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<long>("VersionVector")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version_vector");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_chapters_series_id");

                    b.HasIndex("SeriesId", "ChapterNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_chapters_series_number");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("element_type");

                    b.Property<Guid>("PanelId")
                        .HasColumnType("uuid")
                        .HasColumnName("panel_id");

                    b.Property<Guid?>("ScriptLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("script_line_id");

                    b.Property<Guid?>("SpeakerCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("speaker_character_id");

                    b.Property<string>("StyleProperties")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("style_properties")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("TransformGeometry")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("transform_geometry")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("ZIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("z_index");

                    b.HasKey("Id");

                    b.HasIndex("ScriptLineId");

                    b.HasIndex("PanelId", "ZIndex")
                        .HasDatabaseName("ix_elements_panel_zindex");

                    b.ToTable("elements", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<int>("Dpi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(300)
                        .HasColumnName("dpi");

                    b.Property<int>("HeightPx")
                        .HasColumnType("int")
                        .HasColumnName("height_px");

                    b.Property<string>("LayoutFormat")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("layout_format");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int")
                        .HasColumnName("page_number");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.Property<int>("WidthPx")
                        .HasColumnType("int")
                        .HasColumnName("width_px");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.HasIndex("ChapterId", "PageNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_pages_chapter_number");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Panel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BoundingBox")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("bounding_box")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid?>("CurrentStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_stage_id");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<int>("PanelNumber")
                        .HasColumnType("int")
                        .HasColumnName("panel_number");

                    b.Property<int>("ReadingOrder")
                        .HasColumnType("int")
                        .HasColumnName("reading_order");

                    b.HasKey("Id");

                    b.HasIndex("PageId", "PanelNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_panels_page_number");

                    b.ToTable("panels", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<string>("Heading")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("heading");

                    b.Property<int>("SceneNumber")
                        .HasColumnType("int")
                        .HasColumnName("scene_number");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "SceneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_scenes_chapter_number");

                    b.ToTable("scenes", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.ScriptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DialogueText")
                        .HasColumnType("text")
                        .HasColumnName("dialogue_text");

                    b.Property<int>("LineOrder")
                        .HasColumnType("int")
                        .HasColumnName("line_order");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.Property<Guid?>("SpeakerCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("speaker_character_id");

                    b.Property<string>("StageDirection")
                        .HasColumnType("text")
                        .HasColumnName("stage_direction");

                    b.HasKey("Id");

                    b.HasIndex("SceneId", "LineOrder")
                        .HasDatabaseName("ix_script_lines_scene_order");

                    b.ToTable("script_lines", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ReadingDirection")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reading_direction");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_series_workspace_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.ExternalPreviewLink", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Chapter", null)
                        .WithMany("ExternalPreviewLinks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Auth.User", "CreatedByUser")
                        .WithMany("CreatedPreviewLinks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.StudioWorkspace", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Auth.User", "Owner")
                        .WithMany("OwnedWorkspaces")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.WorkspaceMember", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Auth.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Auth.StudioWorkspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Chapter", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Series", "Series")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Element", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Panel", "Panel")
                        .WithMany("Elements")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Content.ScriptLine", "ScriptLine")
                        .WithMany("BoundElements")
                        .HasForeignKey("ScriptLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Panel");

                    b.Navigation("ScriptLine");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Page", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Chapter", "Chapter")
                        .WithMany("Pages")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanelForge.Domain.Entities.Content.Scene", "Scene")
                        .WithMany("Pages")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Panel", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Page", "Page")
                        .WithMany("Panels")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Scene", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Chapter", "Chapter")
                        .WithMany("Scenes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.ScriptLine", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Content.Scene", "Scene")
                        .WithMany("ScriptLines")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Series", b =>
                {
                    b.HasOne("PanelForge.Domain.Entities.Auth.StudioWorkspace", "Workspace")
                        .WithMany("Series")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.StudioWorkspace", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Auth.User", b =>
                {
                    b.Navigation("CreatedPreviewLinks");

                    b.Navigation("OwnedWorkspaces");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Chapter", b =>
                {
                    b.Navigation("ExternalPreviewLinks");

                    b.Navigation("Pages");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Page", b =>
                {
                    b.Navigation("Panels");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Panel", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Scene", b =>
                {
                    b.Navigation("Pages");

                    b.Navigation("ScriptLines");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.ScriptLine", b =>
                {
                    b.Navigation("BoundElements");
                });

            modelBuilder.Entity("PanelForge.Domain.Entities.Content.Series", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
